# Generated by Django 3.2.9 on 2021-12-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='creator',
        ),
    ]
