# Generated by Django 3.2.9 on 2021-12-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_remove_entry_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
